### ISSUE TITLE
Error with alphanumeric residue numbers

### ISSUE THREAD

**Issue by dharux** [Valdes-Tresanco-MS/gmx_MMPBSA#134]
gmx_MMPBSA throws an error when some of the residues has an alphanumeric residue number, eg. 27A.

System type: Protein-Protein
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8009565/gmx_MMPBSA.log)
[out.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8009568/out.txt)

**Comment by Valdes-Tresanco-MS** [comment]
Yes, we know  about this issue. In fact I just responded to the same error. Please, check this [thread](https://groups.google.com/g/gmx_mmpbsa/c/_AgxdIE0R1I) and tell me if with that proposal you manage to carry out the calculations.
We are evaluating the alternatives to solve this problem without depending on the official versions of parmed, since they go at a different rate than ours.

Mario S.

**Comment by dharux** [comment]
I tried the method you prescribed. It seems to help a bit and progressed a bit further in the pipeline but throws a different error.
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8009777/gmx_MMPBSA.log)
[out.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8009778/out.txt)

**Comment by Valdes-Tresanco-MS** [comment]
But this error is related to the input file. Please send me the files to test (*.tpr, 5-10 frames *.xtc, *.ndx, *.top with all files associated and the mmpbsa.in)

**Comment by dharux** [comment]
I am attaching a sample of the files giving this error. Please check and see what is going wrong.
[Sample.zip](https://drive.google.com/file/d/1vMM9iiEMSDas6c9KMwIUDx4VEJbKtc0f/view?usp=sharing)

**Comment by Valdes-Tresanco-MS** [comment]
Please, send me the mmpbsa.in file

**Comment by dharux** [comment]
Sorry, that got missed out in the zip file. Here it is.
[mmpbsa.in.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8012627/mmpbsa.in.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Please, update ParmEd since the master branch not work properly
`pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd@v3.4 -U`
After update it, it work as expected

Mario S.

**Comment by dharux** [comment]
Yes, this fixes the issue. Thanks!

**Comment by Valdes-Tresanco-MS** [comment]
They just accepted these modifications in the official Parmed repository, so we will eventually change the installation instructions for their use.
Now can be installed via 

    pip install git+https://github.com/ParmEd/ParmEd@v3.4 -U

**Comment by Valdes-Tresanco-MS** [comment]
Officially solution.

1. `conda create -n gmxMMPBSA python=3.9` (Create a new conda environment, to avoid compatibility problems)
2. `conda activate gmxMMPBSA`
3. `conda install -c conda-forge mpi4py ambertools=21 compilers`
4. `pip install git+https://github.com/ParmEd/ParmEd@v3.4 -U` (updates ParmEd from the official Github repository, since they accept the PR)
5. `python -m pip install PyQt5 gmx_MMPBSA`
