### ISSUE TITLE
is print_res necessary while doing decomposition?

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#135]
**Describe the issue**
A clear and concise description of what the issue is.

I want to do a decomposition analysis with gb. do i need to define print_res?
this is my input file:
&general
startframe=1, interval=1,temperature=310
verbose=1, keep_files=0,
strip_mask=":WAT:CLA:SOD"
/
&gb
igb=5, saltcon=0.154
/
&decomp
idecomp=2, dec_verbose=2, csv_format=1
/

Thanks

**Comment by Valdes-Tresanco-MS** [comment]
The `print_res` variable has a default value (`"within 6"`) which means that it is not necessary to define it explicitly. This value will extract all residues less than 6Å between receptor and ligand and calculate their energy contribution depending on the value of `idecomp`. Check this [section ](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#decomp-namelist-variables)
Note that the default value can comprise a considerable amount of residues, so if you are only interested in a few, you may want to define them yourself.
In the new version, we have improved several aspects related to this. We hope to release it soon.

**Comment by hima111997** [comment]
Thank you
However, in MMPBSA.py the default is to print all the residues of the protein. How can i do this in GMX_MMPBSA?

**Comment by hima111997** [comment]
Sorry i checked the link and found that there was a tab named all.
Thanks for your reply

**Comment by Valdes-Tresanco-MS** [comment]
> Thank you However, in MMPBSA.py the default is to print all the residues of the protein. How can i do this in GMX_MMPBSA?

Note that although **gmx_MMPBSA** is based on **MMPBSA.py**, it currently outperforms it in many usability aspects. In our documentation, you will find everything you need.

Note that the decomposition takes computation time and generates a considerable amount of data. **gmx_MMPBSA_ana** should be able to deal with that, but some graphics like heatmaps or bars can be seriously affected both in aesthetics and performance.
I advise you to carry out the analysis on a relatively small set of residues or by distance selection, and if it does not meet your needs, do it for all. But feel free to do it however you want and let us know if you have any problems.

Note: The variable `strip_mask` does not need to be defined, since this is done internally by **gmx_MMPBSA**. It appears in the documentation for the new version (v1.5.0) that we are developing and by mistake, we have mixed everything. We will do our best to improve this for future versions.

@marioernestovaldes, please clarify this in the documentation

Happy energy calculation!

Mario S.
