### ISSUE TITLE
unable to calculate correlation between systems

### ISSUE THREAD

**Issue by enazbngl** [Valdes-Tresanco-MS/gmx_MMPBSA#137]
Hello,
I performed gb and energy decomposition of multiple systems. My folder system is like suggested in the documentation and the command i use to open analyzer is: `gmx_MMPBSA_ana -f . -r`
Eventhough the systems can be seen in the _Initialization gmx_MMPBSA_ana_  window I get "**unable to calculate correlation** " error after processing and the program simply open the energy plot window.

**Comment by Valdes-Tresanco-MS** [comment]
Unfortunately, this feature has always been experimental, since we have not been able to test it much, nor do many users use it, so we have not had any feedback. In the new version, there are significant changes so this feature will initially be disabled.
In any case, check that the systems are homogeneous, that is, that they have the same types of calculations. In our initial tests, only the GB and PB calculations were included and nothing else.
We are sorry that we cannot give you the appropriate support. I will leave the issue open to keep it pending in the re-implementation of this feature
