### ISSUE TITLE
[Question]: is gmx_MMPBSA able to read input files from charmm-gui?

### ISSUE THREAD

**Issue by purnawanpp** [Valdes-Tresanco-MS/gmx_MMPBSA#149]
### My Question is...

is gmx_mmpbsa able to read input files from charmm-gui ? I have used amberf f14SB forcefield for protein and gaff2 for ligand, I tried to do calculations with protein 3htb with ligand code JZ4 I always get an error message, namely: 

```
MMPBSA_Error /home/renoir/Programs/Gromacs/gromacs-2021.5/build/bin/gmx editconf failed when querying step5_1.tpr.            Check the gmx_MMPBSA.log file to report the problem.   
File "/home/renoir/Software/Amber20_cuda/miniconda/bin/gmx_MMPBSA", line 8, in <module>    
 sys.exit(gmxmmpbsa())   
File "/home/renoir/Software/Amber20_cuda/miniconda/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 95, in gmxmmpbsa     app.make_prmtops()   
File "/home/renoir/Software/Amber20_cuda/miniconda/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 576, in make_prmtops     self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()   
File "/home/renoir/Software/Amber20_cuda/miniconda/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 115, in buildTopology     self.gmx2pdb()   
File "/home/renoir/Software/Amber20_cuda/miniconda/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 166, in gmx2pdb    
GMXMMPBSA_ERROR('%s failed when querying %s' % (' '.join(self.editconf), self.FILES.complex_tpr))   
File "/home/renoir/Software/Amber20_cuda/miniconda/lib/python3.9/site-packages/GMXMMPBSA/exceptions.py", line 169, in __init__    
raise exc(msg + '. Check the gmx_MMPBSA.log file to report the problem.') 
MMPBSA_Error: /home/renoir/Programs/Gromacs/gromacs-2021.5/build/bin/gmx editconf failed when querying step5_1.tpr. 
Check the gmx_MMPBSA.log file to report the problem. Exiting. All files have been retained.
```

**Comment by marioernestovaldes** [comment]
Please, could you send the gmx_MPBSA.log file?

thanks in advance

**Comment by purnawanpp** [comment]
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8106569/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment]
I see you are using the following command line:

`gmx_MMPBSA -O -i mmpbsa.in -cs step5_1.tpr -ci index.ndx -cg 1 13 -ct step5_1.xtc -lm JZ4.mol2`

According to this command line, the binding free energy will be calculated between groups 1 and 13 of the index file... These groups are supposed to be the receptor and the ligand, however in your index file the group 1 is the entire complex and 13 is inexistent... As expected this ended up in error... make sure the groups in the index file are well defined... check this [tutorial](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Protein_ligand/ST/) on how to calculate binding free energies for protein-ligand complexes with gmx_MMPBSA... Also it's strongly recommended to read the [howworks section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/howworks/) in order to get better understandign on how gmx_MMPBSA works...

cheers!

**Comment by purnawanpp** [comment]
Thank you. I have used gmx_mmmpbsa with Justin Lemkul's MD tutorial and it worked, but when I prepare proteins and ligands in charmmgui I see index.ndx only holds 0-3 groups.

**Comment by marioernestovaldes** [comment]
Yes, charmm-gui only needs those groups, however for using gmx_MMPBSA you need to define groups containing the receptor and the ligand, respectively...
