### ISSUE TITLE
[ENH]: Add new radii sets...

### ISSUE THREAD

**Issue by marioernestovaldes** [Valdes-Tresanco-MS/gmx_MMPBSA#161]
### New Feature

[Yamagishi et al. radii set](https://onlinelibrary.wiley.com/doi/10.1002/jcc.23728)

- From performance evaluations on large peptides using the newly obtained PB radii, our PB showed a high estimation accuracy of solvation free energies

[Tan, Yang  and Luo radii set](https://pubs.acs.org/doi/full/10.1021/jp063479b)

- Named `TYL06.DAT` in pdb2pqr dat folder

Eventually, remove radiopt option???

[OPT1 radii set](https://pubs.acs.org/doi/10.1021/acs.jctc.0c00142)

- Globally optimized atomic (and water probe) radii for protein-ligand complexes obtained with the new pipeline (includes a highly parallel optimization approach (VTDIRECT95)) and a highly accurate numerical GB model (GBNSR6)

check for more raddi sets at http://compbio.clemson.edu/media/download/parameters.tar.gz

### Relevance

low

### Difficulty to implement

low

**Comment by Valdes-Tresanco-MS** [comment]
> ### New Feature
> [Yamagishi et al. radii set](https://onlinelibrary.wiley.com/doi/10.1002/jcc.23728)
> 
> * From performance evaluations on large peptides using the newly obtained PB radii, our PB showed a high estimation accuracy of solvation free energies

It looks pretty good, but the list of PB radii is huge. It looks like we will have quite a bit of work to implement and debug this radii set. We will definitely have to do it by grouping by atom type or the code will be absurdly long. A reasonable option may be to make it similar to pdb2pqr, storing this data in a file, in this way the code is cleaner and we can better manage the data according to the atom type. Is this option good for you @marioernestovaldes, @swails?

**Comment by swails** [comment]
"Atom Type" is not well-defined in ParmEd because it gets them from all sorts of source file formats.  This includes file formats that don't actually have atom types (like OpenMM) where ParmEd is left to essentially make them up.

I'd love to extract these into a rules file of some sort, but I don't know offhand how to make it flexible enough to do what it currently does.

As an intermediate, we could extract each assignment function to its own module to avoid cluttering and bloating the file they're all currently in.

This is probably good enough for most use-cases.

**Comment by Valdes-Tresanco-MS** [comment]
We will work on a proposal after thoroughly reviewing all the PB radii we have, both implemented and new. Hopefully, we can unify everything into one set of rules
