### ISSUE TITLE
[Question]: usage of gmx_MMPBSA with a trajectory containing three or more different types of molecules

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#199]
### My Question is...

is it possible to use the gmx_MMPBSA tool with a trajectory containing three or more different types of molecules (small molecule - protein - nucleic acid) to calculate the affinity for just two of them (protein and small molecule)?

**Comment by marioernestovaldes** [comment]
Yes, it is.... Check this tutorial on binding free energy calculations in multicompoment systems 

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Comp_receptor/

**Comment by hima111997** [comment]
thank you. But if i have a peptide and small molecule binding to a protein in two sites near each other and i want to get the affinity and decomposition of the peptide with the protein only. How can i do this? should i select the two groups related to the protein and the peptide (assuming that there is one group for each object in the index file or should i merge the protein with the ligand as one group and consider it as the receptor)?

**Comment by marioernestovaldes** [comment]
_should i select the two groups related to the protein and the peptide (assuming that there is one group for each object in the index file_

this sounds reasonable if you are interested only in describing the interaction of the peptide with the protein (without considering the possible effect of the ligand on this interaction)

_should i merge the protein with the ligand as one group and consider it as the receptor)?_

this sounds reasonable if you are interested in describing the interaction of the peptide with the protein considering the possible effect of the ligand on this interaction. If you are going with this one, make sure you define the topology with '-cp' flag because it is the approach that supports small ligands as part of the receptor in gmx_MMPBSA

hope this helps!
