### ISSUE TITLE
[Question]: what is the country of gmx_MMPBSA program?

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/gmx_MMPBSA#270]
### My Question is...

a reviewer asked us to add the country of the gmx_MMPBSA package. Can you tell us what it the country or the university?

**Comment by marioernestovaldes** [comment]
If you use this citation:

Valdés-Tresanco, M.S., Valdés-Tresanco, M.E., Valiente, P.A. and Moreno E. gmx_MMPBSA: A New Tool to Perform End-State Free Energy Calculations with GROMACS. Journal of Chemical Theory and Computation, 2021 17 (10), 6281-6291. https://pubs.acs.org/doi/10.1021/acs.jctc.1c00645

There is absolutely no need to mention the country since it is a combine effort...

**Comment by hima111997** [comment]
thank you
