### ISSUE TITLE
[Question]: running PBS script

### ISSUE THREAD

**Issue by prasannavd** [Valdes-Tresanco-MS/gmx_MMPBSA#271]
### My Question is...

Thank you for the great tool! I tried to run the following command in PBS script but cannot. However, works fine when I activate the conda evironment and run in the terminal. I also tried the HPC script mentioned in https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/gmx_MMPBSA_running/?h=pbs 
for p in `cat ligandlist.txt`;do nn=`basename $p`; gmx_MMPBSA -O -i mmpbgbsa.in  -cs ../$p/md_0_1.tpr -ci ../$p/index.ndx -cg 1 13 -ct ../$p/md_0_1_mmpbgbsa_$nn.xtc -cp ../$p/peptide.top -o ../$p/mmpbgbsa_$nn.dat; done

**Comment by Valdes-Tresanco-MS** [comment]
What is your question? It seems that your description is incomplete.

**Comment by prasannavd** [comment]
Please check the question now! My PBS script is as follows

#PBS -N gmx_mmpbsa
#PBS -q long
#PBS -S /bin/sh
#PBS -M 
#PBS -e localhost:$HOME/myjob.err
#PBS -o localhost:$HOME/myjob.log
#PBS -l nodes=anode10:ppn=20
cd $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
for p in `cat ligandlist.txt`;do nn=`basename $p`; gmx_MMPBSA -O -i mmpbgbsa.in  -cs ../$p/md_0_1.tpr -ci ../$p/index.ndx -cg 1 13 -ct ../$p/md_0_1_mmpbgbsa_$nn.xtc -cp ../$p/peptide.top -o ../$p/mmpbgbsa_$nn.dat; done
exit 0

**Comment by Valdes-Tresanco-MS** [comment]
I am not completely familiar with PBS since I have not interacted with it for several years. However, if I remember correctly you must activate the conda environment within the PBS script. In most HPCs there are modules that allow you to have duplicate applications with different versions. In many cases, you already have a conda environment. 
Here is an example of how I think it should be. There are several options, according to your availability, you should use one or another. Additionally, consider the improvements that I suggest.

```bash
#PBS -N gmx_mmpbsa
#PBS -q long
#PBS -S /bin/sh
#PBS -M
#PBS -e localhost:$HOME/myjob.err
#PBS -o localhost:$HOME/myjob.log
#PBS -l nodes=anode10:ppn=20
cd $PBS_O_WORKDIR
echo Running on host hostname
echo Time is date
echo Directory is pwd
##########################################################################
### This option use the local conda environment
wget https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/env.yml
conda create -n gmxMMPBSA --file env.yml
conda activate gmxMMPBSA

### This option assumes a module containing gmx_MMPBSA
## module load gmx_mmpbsa/1.5.6-gcc-9.3.0
## gmx_MMPBSA_1.5.6
##########################################################################
## Command results in bash are only accessible when they are used between quotes.
for nn in `cat ligandlist.txt`;
do 
  ## basename requires a pattern, so this command is wrong. Assuming this file only contains the name of each ligand, you can 
  ## use $nn (previously $p) in the following commands
  ## nn=basename $p; 

  ### You may want to create a folder for each calculation.
  mkdir $nn
  cd $nn
  ### Consider use MPI for calculations. Assuming CPU=20
  mpirun -np 20 gmx_MMPBSA MPI -O -i mmpbgbsa.in -cs ../$p/md_0_1.tpr -ci ../$p/index.ndx -cg 1 13 -ct ../$p/md_0_1_mmpbgbsa_$nn.xtc -cp ../$p/peptide.top -o ../$p/mmpbgbsa_$nn.dat -nogui
  cd ..
done

exit 0
```
Please check that the for loop works correctly on your machine before sending it to your HPC queue. You can replace the command that invokes gmx_MMPBSA with a notification for the test. Make sure that each folder is being created correctly and that the calculations are executed in it, since if all calculations are overwritten, you would lose all related information, leaving only the file you defined in the -o option.
HTH!

**Comment by Valdes-Tresanco-MS** [comment]
Closed due to inactivity
