### ISSUE TITLE
MMPBSA_Error Could not import PyQt5/PyQt6

### ISSUE THREAD

**Issue by bee-wulf** [Valdes-Tresanco-MS/gmx_MMPBSA#272]
Hello, sorry to bring up a topic that I've seen been resolved and closed several times over the last year; however, none of those resolutions #62  #208 #176 #100 could seem to resolve this recurrent error on my end. I am on an HPC cloud server where the root folder is reset after each logout. I have my conda environments in my personal directory as examined from below: 
[gmx_MMPBSA_ana error.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9189562/gmx_MMPBSA_ana.error.txt)

I have tried multiple fresh installs following the various protocols, beginning with a user from last year: 
conda create -n pbsa2 -c conda-forge setuptools=47.0 ambertools=21 compilers python=3.6 
conda activate pbsa2
conda install -c conda-forge mpi4py
python -m pip install gmx_MMPBSA 
python -m pip install pyqt5

This protocol seemed to work, for I avoided the pyqt error. However, I encounted: "t.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

I updated libxcb and the other dependencies, but I then resolved to try a fresh install of this whole process again, but with python 3.9. For this, I installed: 
conda create -n pbsa -c conda-forge setuptools ambertools python=3.9
Which got me setuptools>60, amber 22
conda activate pbsa
conda install -c conda-forge mpi4py
python -m pip install gmx_MMPBSA 
python -m pip install pyqt6 

pyqt6 gave me a metadata generation error, so I reverted back to pyqt5. After successful installation, I came back to the initial error I received when I did my very first installation of gmx_MMPBSA which is this PyQt5 not found error. 

Hope this is not too redundant from past posts! I appreciate the help immensely!

**Comment by Valdes-Tresanco-MS** [comment]
No problem, we will solve it as many times as necessary, don't worry.
Normally, HPCs do not have graphics drivers, especially if they are virtual machines. This means that the system cannot find the graphics engine to render windows. I am not very familiar with your HPC in the cloud, but this is probably what happens. In other cases, the kernel of the OS that uses your HPC can be quite old (for example, Centos 7), which makes that the new graphic libraries are not supported. It can be solved by exporting the updated libraries from conda as mentioned [here](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues/208#issuecomment-1082037051). Note, that this will only work if your user has access permissions to the OS GUI, whether you run it locally or via ssh, if you don't have an output port for graphics, no matter what you do, you won't be able to launch GUIs. This seems to be the procedure for [installing/launching GUIs on AWS](https://aws.amazon.com/es/premiumsupport/knowledge-center/ec2-linux-2-install-gui/), but I'm not sure if it's feasible for other services or even a seamless experience. 
If none of the above works, don't worry, you can always run the scans on your PC, as they are not heavy at all. To do this, just download the working folder from the cloud server to your PC and run `gmx_MMPBSA_ana [-f to the path if necessary]` on the folder and you're done.
If for some reason, or simplicity, you want to do a quick test, you can just download the `COMPACT_MMXSA_RESULTS.mmxsa` file and run `gmx_MMPBSA_ana -f /path/to/COMPACT_MMXSA_RESULTS.mmxsa` and that's it, you will be able to visualize the results. Note, however, that this file does not allow modifications to rewrite the output files.

**Comment by bee-wulf** [comment]
Thank you, sir. I did have the thought yesterday about running the GUI processes on the HPC. But, I'm a new student in this field, so I wasn't quite sure. Ok. Now, I see why #208 did nothing for me when I change the LD_LIBRARY_PATH. Just to clarify, I can run gmx_MMPBSA_ana locally on Windows? In such a case, do I still need to download AmberTools or just the gmx_MMPBSA and singularly use ana?

**Comment by Valdes-Tresanco-MS** [comment]
Exporting `LD_LIBRARY_PATH` helps when there is a library compatibility problem, commonly on Centos 7 or Debian <8. Normally, it is not possible to run GUI on HPC because it is explicitly disabled by administrators. If your connection is via ssh you will most likely not be able to do so. If it still does not work, even after running all the options discussed in the issues you reference, it means that HPC simply does not support GUIs.
Unfortunately, gmx_MMPBSA (including gmx_MMPBSA_ana) is not supported on Windows, only Linux, and macOS. I will try to implement it in the future but it may take some time. However, theoretically (I have not been able to validate it yet) you can use the Windows Subsystem for Linux which supports native Linux GUIs (Windows 11 only), or the Docker package (both require some work).

**Comment by Valdes-Tresanco-MS** [comment]
Check this [solution](https://www.youtube.com/watch?v=BDilFZ9C9mw) for docker with GUI support in Windows

**Comment by bee-wulf** [comment]
Ah, I understand. I appreciate the assistance. I will look into those workarounds. But, would you be able to recommend another means by which I can plot these data? I have the per residue decomp analysis in .dat form and .csv. I've tried to use R and Python IDE's, but my plotting knowledge is still basic in those programs. 
Thank you kindly

**Comment by Valdes-Tresanco-MS** [comment]
The main advantage of gmx_MMPBSA_ana is that it makes available to the user most of the graphs used in this type of study with just a few clicks. The csv format contains the raw data, while the dat file contains only a summary. Doing what is done with gmx_MMPBSA_ana is not impossible, but it takes a lot of work. So much so, that gmx_MMPBSA_ana is the application that has evolved the most, having only releases dedicated to its improvement and optimization. Unfortunately, for lack of time I have not been able to fully develop the API documentation, but with it is that you can do all the graphics shown in gmx_MMPBSA_ana. We have it in plans for implementation on Jupyter notebooks, but it may take some time.
In my opinion, you should try to use gmx_MMPBSA_ana before diluting yourself in looking for alternatives to make the graphs from raw data. This would require, not only programming knowledge but deep knowledge of data structuring (vaguely explained in the documentation, my fault). This could take a significant amount of time, which is why we created gmx_MMPBSA_ana. We have invested the time so that the user can focus on what is really important, the analysis. 
A viable solution would be to install a virtual machine with VirtualBox, as there are many tutorials and it is very simple.

**Comment by bee-wulf** [comment]
Okay Thank you, sir. I'll continue working with gmx_MMPBSA_ana. I'll exhaust the resources you just gave me, but I agree that I will likely move towards a virtual machine.

**Comment by Valdes-Tresanco-MS** [comment]
If we have exhausted the options with the main idea of the issue and you think it has been solved, please close it. If you have another problem or concern, you can use our group, to open another issue or write me an email if confidential.
Let me know if I can help you with anything else

**Comment by bee-wulf** [comment]
![image](https://user-images.githubusercontent.com/108278411/181181213-f221ffd9-b143-4aa4-a926-437ec24ffa1d.png)
It works with the virtual machine! Thank you, sir! Closing, now.

**Comment by bee-wulf** [comment]
![image](https://user-images.githubusercontent.com/108278411/181181213-f221ffd9-b143-4aa4-a926-437ec24ffa1d.png)
It works with the virtual machine! Thank you, sir! Closing, now.
