### ISSUE TITLE
[Question]: About the accuracy

### ISSUE THREAD

**Issue by giangpth** [Valdes-Tresanco-MS/gmx_MMPBSA#278]
### My Question is...

Hello, I tried to run some calculation based on some experimental data, and I didn't get the result like the experiment relatively (I mean the order of free energy values for complexes). I am aware that many things may go wrong in my calculation but can you give me some idea what should I check to get a better result? Thank you.

**Comment by Valdes-Tresanco-MS** [comment]
You can hardly obtain the experimental energy using end-point methods. Generally, these methods tend to overestimate the predicted energy and be system-dependent. It is recommended to use it as relative energy for comparisons between a set of ligands since the error is assumed to be similar in all cases. It is also necessary and convenient to explore the parameters that best fit the nature of your system, since at least in gmx_MMPBSA you can calculate 32 absolute energy combinations, not counting the parameters that influence the prediction such as the internal dielectric constant, just to give an example.

**Comment by giangpth** [comment]
Yes, my aim is to compare different ligands but not calculate the absolute binding free energy. 
Thank you for your answer. I will close the issue and play with the parameters.

**Comment by Valdes-Tresanco-MS** [comment]
[This article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4487606/) is very good in describing the accuracy of the MMPB/GBSA method.
HTH!
