### ISSUE TITLE
[Question]: How to understand the FINAL_DECOMP_MMPBSA.dat file?

### ISSUE THREAD

**Issue by Clare-xiong** [Valdes-Tresanco-MS/gmx_MMPBSA#296]
### My Question is...

I am doing the decomposition analysis, but it only returns the FINAL_DECOMP_MMPBSA.dat, I didn’t get FINAL_DECOMP_MMPBSA.csv. And dec_verbose=3, I don’t know how to read the file FINAL_DECOMP_MMPBSA.dat, where can I get the document described this file?

**Comment by Valdes-Tresanco-MS** [comment]
Oh, you are right, this file is not described in the documentation. Actually, the `FINAL_DECOMP_MMPBSA.csv` file is not generated, we simply change the output format of `FINAL_DECOMP_MMPBSA.dat` depending on the variable `csv_format`. If you use the default value (`csv_format=1`), this file will be in CSV format, otherwise, it will be in ASCII format (more aesthetic table).
This file has the following layout:

Per-residue (`idecom = [1 or 2]`)
|  Residue   |     Internal      |   van der Waals   |   Electrostatic   |  Polar Solvation  | Non-Polar Solv.  |      TOTAL       |
|:----------:|:-----------------:|:-----------------:|:-----------------:|:-----------------:|:----------------:|:----------------:|
|    name    |    value + std    |    value + std    |    value + std    |    value + std    |   value + std    |   value + std    |
| R:A:ALA:11 | 10.772 +/-  2.255 | -3.757 +/-  0.862 | -1.888 +/-  1.645 | -0.064 +/-  0.194 | 0.000 +/-  0.000 | 5.063 +/-  2.928 |

Per-wise (`idecom = [3 or 4]`)
|   Res-1    |   Res-2    |     Internal      |   van der Waals   |   Electrostatic   |  Polar Solvation  | Non-Polar Solv.  |      TOTAL       |
|:----------:|:----------:|:-----------------:|:-----------------:|:-----------------:|:-----------------:|:----------------:|:----------------:|
|    name    |    name    |    value + std    |    value + std    |    value + std    |    value + std    |   value + std    |   value + std    |
| R:A:ALA:11 | R:A:ALA:11 | 10.772 +/-  2.255 | -3.757 +/-  0.862 | -1.888 +/-  1.645 | -0.064 +/-  0.194 | 0.000 +/-  0.000 | 5.063 +/-  2.928 |

In your case, as you selected `dec_verbose = 3`, a table similar to the previous ones will be displayed for each structural component (Total Decomposition Contribution -TDC, Sidechain Decomposition Contribution - SDC and Backbone Decomposition Contribution - BDC) of the Complex, Receptor, Ligand and Delta (12 tables).
Unless you are interested in mutating amino acids and want to estimate which ones contribute their side chains, TDC should be sufficient. This way you simplify the output and make it a bit more understandable.
If you want to make your own graphs, the recommendation is to use the csv format (`csv_format = 1`), since it is a standard format. **gmx_MMPBSA_ana** simplifies any analysis you want to do and allows you to export subsets of data. You can check the previous version of **gmx_MMPBSA_ana** in action in the per-residue analysis [here](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/analyzer/#per-residue-decomposition)

**Comment by Clare-xiong** [comment]
Thanks for your reply! And I want to know how to save the picture from gmx_MMPBSA_ana?

**Comment by Clare-xiong** [comment]
Thanks for your reply! I find it is not all the residues in the FINAL_DECOMP_MMPBSA.dat are showed in the gmx_MMPBSA_ana, and the value is not match. In my file FINAL_DECOMP_MMPBSA.dat, the total value of residue 209 is 37.51kcal/mol, however the value is between -2.5 and 0kcal/mol in the picture of gmx_MMPBSA_ana. Do I misunderstand?

**Comment by Clare-xiong** [comment]
Thanks for your reply! I find it is not all the residues in the FINAL_DECOMP_MMPBSA.dat are showed in the gmx_MMPBSA_ana, and the value is not match. In my file FINAL_DECOMP_MMPBSA.dat, the total value of residue 209 is 37.51kcal/mol, however the value is fall in range (-2.5,0) in the picture of gmx_MMPBSA_ana. Why is there a difference? Do I misunderstand?

**Comment by Clare-xiong** [comment]
Thanks for your reply! I find it is not all the residues in the FINAL_DECOMP_MMPBSA.dat are showed in the gmx_MMPBSA_ana, and the value is not match. for example, in my file FINAL_DECOMP_MMPBSA.dat, the total value of residue 209 is 37.51kcal/mol, however the value is fall in range (-2.5,0) in the picture of gmx_MMPBSA_ana. Why is there a difference? Do I misunderstand?

**Comment by Clare-xiong** [comment]
Thanks for your reply! I find it is not all the residues in the FINAL_DECOMP_MMPBSA.dat are showed in the gmx_MMPBSA_ana, and the value is not match. for example, in my file FINAL_DECOMP_MMPBSA.dat, the total value of residue 209 is 37.51kcal/mol, however the value is fall in range (-2.5,0) in the picture of gmx_MMPBSA_ana. Why is there a difference? Do I misunderstand? And How to save the picture showing in the gmx_MMPBSA_ana?

**Comment by Clare-xiong** [comment]
Thanks for your reply. Here is the file COMPACT_MMXSA_RESULTS.mmxsa
[COMPACT_MMXSA_RESULTS.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9943349/COMPACT_MMXSA_RESULTS.zip)

**Comment by Valdes-Tresanco-MS** [comment]
I think you made a mistake. `37.51` corresponds to the energy value (TDC) of the residue `R:A:PHE:209` of the complex. The DELTA value (at the end of the `FINAL_DECOMP_MMPBSA.dat` file) for that residue is `-0.92` as shown in the graph. Using the initial dialog, you can select which molecules to display. 
![image](https://user-images.githubusercontent.com/36672242/200125290-4b858de8-10e7-41fa-88f5-a51365c4bbcb.png)
Let me know if it clears up your doubts

**Comment by Clare-xiong** [comment]
Yes, thanks for your help, it clears up my doubts. And how do I understand LIG item?

**Comment by Valdes-Tresanco-MS** [comment]
Specifically, what don't you understand about the ligand? Also, their values match both the output file and the graph in **gmx_MMPBSA_ana**. The ligand has no BDC because it is not an amino acid and the values are computed as Residue<sub>COM</sub> - Residue<sub>LIG</sub>, just like for the receptor.
Let me know your doubts

**Comment by Clare-xiong** [comment]
Does all the delta value add up to the binding free energy? And does the ligand value means its contribution to the binding free energy? Does decomposition analysis mean break down the energy that drives the binding of the compound to each amino acid residue? If that, why does the result have the LIG value?

**Comment by Valdes-Tresanco-MS** [comment]
The energy decomposition consists of estimating the interaction energy either per-residue or per-wise. In the first case, the DELTA energy corresponds to the sum of the interaction energy of that residue with the rest of the selected residues and itself. In the second case, it is computed in pairs, i.e., the interaction energy between two residues. This is an approximation, which is not equivalent to the relative binding free energy value since it is computed only between the selected residues. The decomposition aims to estimate which residues are apparently more important for the interaction, useful when generating mutants (e.g. peptide design, in silico affinity maturation, etc.) In your case, the energy value reported for the ligand corresponds to the sum of the interaction energies between the ligand and the selected residues and itself. The complex interaction energy (ΔH) is reported in the file FINAL_RESULT_MMPBSA.dat.
