### ISSUE TITLE
Question on Metalloprotein-ligand binding

### ISSUE THREAD

**Issue by leiqian-nmsu** [Valdes-Tresanco-MS/gmx_MMPBSA#349]
### My Question is...

Dear users, In metalloprotein-ligand binding case, I would like to know (1) why intdiel is set to 5 (for the whole protein property, intdiel may not equal to 5); (2) why PBRadii=4(igb=8) are used rather than PBRadii=3; (3) I found a typo in each tutorial, "-cg 3 4" should be "-cg 4 5", by the way I think previous -cg index might be straightforward although not easy to remember

**Comment by Valdes-Tresanco-MS** [comment]
@marioernestovaldes Please, check this info.
@leiqian-nmsu Thank you for carefully reviewing gmx_MMPBSA and reporting your concerns to us.
What specifically are you referring to regarding the definition of the groups? We have implemented both definitions by number and name (recently implemented #157). To avoid having many more flags than gmx_MMPBSA already has and the conflict and confusion with the individual groups of the receptor (`-rg`) and the ligand (`-lg`) in Multiple Trajectory Approximation, we decided to simplify it with the notation `-cg rec_group lig_group`. In any case, suggestions are always welcome. Let us know how you would define it, and we will do our best to implement it.

**Comment by marioernestovaldes** [comment]
> ### My Question is...
> Dear users, In metalloprotein-ligand binding case, I would like to know (1) why intdiel is set to 5 (for the whole protein property, intdiel may not equal to 5); (2) why PBRadii=4(igb=8) are used rather than PBRadii=3; (3) I found a typo in each tutorial, "-cg 3 4" should be "-cg 4 5", by the way I think previous -cg index might be straightforward although not easy to remember

Of note, tutorials are meant to show only how gmx_MMPBSA works; although we have tried to use different parameters combinations for users to see how to use these within gmx_MMPBSA. That being said, 

-the `intdiel` is set to 5 since it is a highly polar environment. There is a lot of discussion about "optimal" internal dielectric value; check this recent article of ours (https://pubs.acs.org/doi/10.1021/acs.jpcb.2c07079)
-PBRadii=4 correspond to `mbondi3` born radii which is the recommended radii when using igb8 (GB-Neck2 model)
-the example works fine for me with "-cg 3 4". Could you please share which files are you using?
-As mentioned previously, the way we defined the groups has not changed. Could you please comment on that last observation?

**Comment by leiqian-nmsu** [comment]
@Valdes-Tresanco-MS @marioernestovaldes
Thank you very much for your kind replies, I really appreciate it.
And thank you for the recommended paper, I will read it.
Regarding the "-cg 3 4" issue, I rechecked the index.ndx file in your webpage: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/tree/master/examples/Metalloprotein_ligand. I found this was my mistake because I forgot that the index of the first section starts with 0.
However, in this Metalloprotein_ligand example, calcium ion (atom index: 1885) is associated with the interaction between protein and ligand. So is it necessary for us to consider taking this calcium as a part of the receptor? If so, atom index 1885 might be included in the section [ receptor ] ?
