### ISSUE TITLE
charmm36 force field

### ISSUE THREAD

**Issue by julianaamorim** [Valdes-Tresanco-MS/gmx_MMPBSA#35]
Hello,

I would like to know if gmx_mmpbsa is compatible with charmm36 force field
Thanks...

Best regards

**Comment by Valdes-Tresanco-MS** [comment]
Since gmx_MMPBSA converts the topology when it comes to charmm force field, it supports any version. For compatibility reasons, we recommend charmm27 or charmm36, lower versions may have incompatibility.

Note that although the charmm force field is supported, gmx_MMPBSA does not support pseudo atoms (like LP [lone pairs]) or rarely parameterized atoms.

You can consult the related information in these links:

https://valdes-tresanco-ms.github.io/gmx_MMPBSA/howworks/#topology-preparation
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Protein_ligand_CHARMMff/
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Protein_membrane_CHARMMff/
https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Ribosomal50S_Mycalamide_A/

HTH!

**Comment by julianaamorim** [comment]
Thank you very much for your prompt attention and the links

Have a great weekend
