### ISSUE TITLE
amber.conda: command not found

### ISSUE THREAD

**Issue by hanahg** [Valdes-Tresanco-MS/gmx_MMPBSA#366]
I got the following error after this code: (gmxMMPBSA) anna@ubuntu:~$ amber.conda install pip  

amber.conda: command not found

**Comment by Valdes-Tresanco-MS** [comment]
Please, read the [documentation](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/installation/#installing-gmx_mmpbsa-v15x) carefully. `amber.python` is only available when you install gmx_MMPBSA with the AmberTools compilation, not in the conda environment.

**Comment by hanahg** [comment]
I did as it mentioned at the installation page, but doesn't work

**Comment by Valdes-Tresanco-MS** [comment]
When `gmxMMPBSA` is at the prompt ( `(gmxMMPBSA) anna@ubuntu:~$`), you have already activated the conda environment called `gmxMMPBSA`. So, you will use all the executables in this environment instead of the system. If you are using the AmberTools build, you should export the `AMBERHOME` variable as per the install instructions and disable any active conda environment.
We have tried to make the installation process as simple as possible. In this sense, you should only:
download the env.yml file
```bash
wget https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/env.yml
```
and run
```bash
conda env create -n gmxMMPBSA --file env.yml
```
activate the environment whatever you want to use gmx_MMPBSA
```bash
conda activate gmxMMPBSA
```
That's all. I'm not sure why it doesn't work. Based on the issue above, you are making typos, not an installation issue. This is by far the simplest way. Compiling AmberTools is much more complicated. Based on your information, I can't identify if it is an external problem, such as a failure in the repositories or dependencies. Currently, I am in Cuba, where the internet connection is really bad. However, it works for me with no problem running the instructions above.
Sorry for the inconvenience, and I remain attentive to your doubts.
