### ISSUE TITLE
Surface

### ISSUE THREAD

**Issue by WoutVanEynde** [Valdes-Tresanco-MS/gmx_MMPBSA#371]
Dear,

I have been looking at the different output files, but I cannot seem to find any information about the surface area over time between ligand and receptor. Is there any way to find/calculate this?

Warm regards,
Wout

**Comment by Valdes-Tresanco-MS** [comment]
What do you mean exactly? SASA is calculated for each system component, i.e., complex, receptor, and ligand. Finally, (Com - (Rec + Lig)) are subtracted to obtain the delta. The SASA between receptor and ligand is not specifically computed. If you want to access the non-polar energy values of the solvation ([see this link to know how it is computed](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/introduction/#introduction)) during the trajectory, you can obtain it in the csv files using the -eo option on the command line. If you want to access the computed SASA instead of energy, this is only possible for the GB method (files ending with gb_surf.dat). If you want to compute SASA between receptor and ligand, you could do it through a per-wise decomposition scheme, but that would be done manually. I think there are better ways to do it if your main goal is that and not energy

**Comment by WoutVanEynde** [comment]
Thank you for your clear answer, I got some more clarification from my professor as well.
