### ISSUE TITLE
While running gmxMMPBSA i am getting error

### ISSUE THREAD

**Issue by kunal74** [Valdes-Tresanco-MS/gmx_MMPBSA#376]
### My Question is...

gmxMMPBSA/bin.AVX2_256/gmx make_ndx failed when querying index.ndx

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach the gmx_MMPBSA.log file

**Comment by kunal74** [comment]
I could solve that issue buy putting the required files in mmpbsa folder and then running it . But now a new error is coming. I am attaching the screenshot 
![Uploading IMG20230527160316.jpg…]()

**Comment by kunal74** [comment]
![IMG20230527160316](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/63805674/2b3c10ff-66ee-4154-ad3e-c602c1e4494a)

**Comment by Valdes-Tresanco-MS** [comment]
Please, use the `-cp topol.top` (which does no require `-lm lig.mol2`) in the command line

**Comment by kunal74** [comment]
Hi. I didnot put -lm in command. I used the command line style given the gmx site:

gmx_MMPBSA -O -i mmpbsa.in -cs com.tpr -ci index.ndx -cg 1 13 -ct com_traj.xtc

PLEASE GUIDE ME WHAT CHANGES TO BE DONE.
THANX

**Comment by kunal74** [comment]
Thanx . I will try and let you know the results

**Comment by kunal74** [comment]
Hi. The solution worked. With the given commands the program ran but i am only getting delta H values but no delta G. Please refer attached screenshot

**Comment by kunal74** [comment]
>

**Comment by kunal74** [comment]
![WhatsApp Image 2023-05-30 at 07 55 46](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/63805674/e8cb29a7-90ff-44a1-94bf-a448f7dad1b3)

**Comment by Valdes-Tresanco-MS** [comment]
To get the DG you must define both enthalpy and entropy methods in the input file. Currently, we implemented PB, GB, GBNSR6, and 3D-RISM for enthalpy, Interaction Entropy, C2 Entropy, Normal Modes, and Quasi-Harmonic for entropy. Please, take care which method you use for entropy because the results can be inconsistent. In some cases, you can use only the Enthalpy contribution, which is called Effective Energy, to compare the same nature ligand

**Comment by kunal74** [comment]
Dear Valdes,
Can you kindly guide me how to define enthalpy and entropy in input file. And which is the input file you are referring. I am a newbie in this field. Thanks

**Comment by Valdes-Tresanco-MS** [comment]
The input file is the one in which the calculation parameters are defined. Please, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/)
The most commonly used entropy methods in gmx_MMPBSA are Interaction and C2 Entropies because they do not require extensive computation resources. Please, check this [section](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#entropy-options). You can use Nmode (the gold standard for entropy calculation), but it requires a lot of computational resources.
As I say below, in some cases, the enthalpy component is enough. Actually, if you check the literature, you can find a lot of reports with the "MMPBSA binding free energy", which technically is wrong since the entropy contribution is neglected. It would be more appropriately called Effective Energy.
All methods for enthalpy calculations ([PB](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#pb-namelist-variables), [GB](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#gb-namelist-variables), [GBNSR6](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#gbnsr6-namelist-variables), [3D-RISM](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#rism-namelist-variables)) and [nmode](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#nmode-namelist-variables) are namelist, while Interaction Entropy, C2 Entropy, and QH are defined in the [General namelist](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/input_file/#entropy-options)

You can check these tutorials:
- [Interaction Entropy calculations](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Entropy_calculations/Interaction_Entropy/)
- [NMODE Entropy calculations](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Entropy_calculations/nmode/)
- [C2 Entropy calculations](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/dev/examples/Entropy_calculations/C2_Entropy/)

All the calculations can be performed simultaneously, but take care because it can take a long time

**Comment by kunal74** [comment]
Dear Valdes, I did as you said in the input files and i got the delta G. Thank you for your prompt help. One last thing i would like to ask could you share me a standard research paper where they have used gmxMMPBSA for binding energy calculation. As I am new to this field I would like to read how they have interpreted the results from the module. Thank you again

**Comment by kunal74** [comment]
Also one problem i noticed that the delta G value is coming in positive. Is there anything I am doing wrong

**Comment by Valdes-Tresanco-MS** [comment]
You can search for this problem here and in [Google Groups](https://groups.google.com/g/gmx_mmpbsa) as it is recurring.
Let me know any questions

**Comment by Valdes-Tresanco-MS** [comment]
I closing this issue since the initial concern was solved. Feel free to open another issue with your doubts, questions, or errors
