### ISSUE TITLE
[Question]: The entropy results for each frame

### ISSUE THREAD

**Issue by chaninpark0806** [Valdes-Tresanco-MS/gmx_MMPBSA#383]
### My Question is...

The entropy results for each frame in the FINAL_RESULTS_MMPBSA.csv file are missing in version 1.6.1. How do I check?

**Comment by Valdes-Tresanco-MS** [comment]
It is intentionally not included due to the characteristics of the methods for entropy calculation. For example, C2 Entropy and QH only generate the entropy value. In contrast, Nmodes generate a value for each selected frame that may or may not coincide with the number of frames for which the enthalpy was calculated. In the case of IE, although the cumulative value is generated for each frame, the computed value corresponds to the selected interval.
For all methods, files are generated in the work folder containing the total values and the frames if applicable.
We encourage our users to use gmx_MMPBSA_ana to analyze the result since it contains all the corresponding charts for any term. Also, you can export de data as csv.

**Comment by chaninpark0806** [comment]
Thank you for your response and efforts.
