### ISSUE TITLE
[Question]: Regarding effect of lone pairs in gmx_MMPBSA calculations

### ISSUE THREAD

**Issue by harpreetsingh05** [Valdes-Tresanco-MS/gmx_MMPBSA#386]
### My Question is...

I am calculating gmx_MMPBSA for a protein (having two chains) and a ligand with two lone pairs in human system as well as in Plasmodium system. As per the requirements i have removed Lone pairs and proceeded with the calculations. However, the results are contrsasting to our molecular docking. The lignad was having high binding affinity with Plasmodium instead of Human system. But the gmx_MMPBSa calculations results are otherwise. To get some indights into the role of lone pairs. I generated the hydrogen bonding graphs for both human and plasmodium system with or wothout lone pairs. In human system the hbond graphs are idetical for complexes having ligand with and witout lone pairs. However in plasmodium system the hbond graph witout lone pairs is showing a very one hbonds that too only in few of the frames, while in the complex having lignd with lone pairs, the number of hydrogen bonds varies from 2 to 3 consistently duding the simulation period. I need your guidance regardig your interpretation and also i will be thankful if you could some other way to verify this phenomenon.

**Comment by Valdes-Tresanco-MS** [comment]
Sorry for the delay.
It is hard to know what is going on without knowing the system. According to what is published:

> Empirical force fields in which the electrostatic interactions are represented by atom-centered point charges cannot capture this effect because halogen atoms usually carry a negative charge and therefore interact unfavorably with other electronegative atoms. A strategy to overcome this problem is to attach a positively charged virtual particle to the halogen. https://doi.org/10.1016/j.bmc.2016.06.034

This particle should help to simulate better the interactions of the halogens with the rest of the atoms in the system. However, I am not sure when it would influence the formation of hydrogen bridges. It is also hard to know the influence of the parameters you used to calculate the energy. In this regard, we include several radii sets, please check the documentation.
Comparing the docking result with free energy calculations is somewhat complicated. Usually, we tend to rely more on the ranking obtained by the latter since they correlate better with the experimental values. Additionally, it includes MD simulation, so you can explore various system states, unlike docking where the receiver is practically static.
