### ISSUE TITLE
[Bug-gmx_MMPBSA_ana]: symbol lookup error: /opt/qt-5.14.2/lib/libQt5XcbQpa.so.5: undefined symbol

### ISSUE THREAD

**Issue by Howpow88** [Valdes-Tresanco-MS/gmx_MMPBSA#390]
### Bug summary

symbol lookup error: /opt/qt-5.14.2/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API

This is my error when trying to run gmx_MMPBSA_ana -f
Please advise 

### Terminal output

```bash
gmx_mmpbsa_ana -f
```

### Actual outcome

symbol lookup error: /opt/qt-5.14.2/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API

### Expected outcome

expecting graphical interface to launch

### Python version

3.9

### Installation

conda AmberTools + conda

**Comment by Valdes-Tresanco-MS** [comment]
What operating system are you using? Have you reviewed the issues reported above? They solve similar problems.

**Comment by Howpow88** [comment]
red hat linux, how do i view issues reported that are similar to this issue?

**Comment by Valdes-Tresanco-MS** [comment]
Searching "pyqt" as the filter
![image](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/assets/36672242/8dae20f7-8e17-45f8-a8d6-aab3305b2a7c)

If it is an HPC OS by default, it is not possible to open GUIs, because it is disabled. If you are using the desktop version, then check the reported issues. Usually, it is an incompatibility between the Qt libraries of the OS and the one installed in the conda environment. There are already solutions for this.
