### ISSUE TITLE
[Question]: Prot-Memb-CHARMM decomp result interpretation

### ISSUE THREAD

**Issue by lmk328** [Valdes-Tresanco-MS/gmx_MMPBSA#395]
### My Question is...

Hi, I recently ran a "Prot-Memb-CHARMM" system according to your configuration https://valdes-tresanco-ms.github.io/gmx_MMPBSA/v1.5.6/examples/Protein_membrane_CHARMMff/. I found that in the FINAL_DECOMP_MMPBSA.dat, "Non-Polar Solv." column is all zero, which should be not true for such a system, as I suppose. I want to know how to interpret the real contributions of all the different terms per residue, according to the data file I have. Another issue is the high ΔEDISPER. I am trying to resolve this problem through your instructions, namely using "inp=1" and "use_sav=0", with other parameters unchanged. Here is the result and log files. Thank you very much!
[CXCR2_DIMER_CP_29.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11992467/CXCR2_DIMER_CP_29.zip)

**Comment by Valdes-Tresanco-MS** [comment]
Please, attach this file since it not included in the zip one

**Comment by lmk328** [comment]
Sorry, something wrong happens when creating the zip file. Here is the file. 
[1st mmpbsa.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/11996143/1st.mmpbsa.zip)

**Comment by Valdes-Tresanco-MS** [comment]
I don't remember exactly why this happens. I think it is because since the membrane is being approximated implicitly there is no way to estimate which residues interact directly with the solvent and so it is not computed. These are useful approximations for comparative analysis, but not for absolute contribution calculations. 
Decomposing the solvation energy in this case, should not give accurate results. Depending on your objective, you could compare the electrostatic, van der Waals, and polar contributions of solvation, which are usually the most notable. It is difficult to be absolutely certain of the values you compute in these cases.
