### ISSUE TITLE
[Question]: Recommended values for intdiel and indi for DNA-protein complex.

### ISSUE THREAD

**Issue by WoutVanEynde** [Valdes-Tresanco-MS/gmx_MMPBSA#414]
I would like to calculate energy (and decomposition energy) of a protein-DNA complex using GBSA and PBSA methods, however I wonder what the recommended intdiel and indi values are. In the examples I see that intdiel is set to 10.0 for the GBSA method, however can the same be done for indi?

I also have some questions about the saltconcentration. In the settings the default is set to 0M, but in all/most of the examples it is set to 0.15M. Is there such a big differences between the two or in other words, why is the default not set to 0.15M?

And if I were to use the &alanine_sanning option with the cas_intdiel = 1 option, would this change a lot for my energy and decomposition results due to the assigned intdiel and indi values? Or is this a complete different calculation?

Warm regards and thank you in advance,
Wout Van Eynde

**Comment by marioernestovaldes** [comment]
**_I would like to calculate energy (and decomposition energy) of a protein-DNA complex using GBSA and PBSA methods, however I wonder what the recommended intdiel and indi values are. In the examples I see that intdiel is set to 10.0 for the GBSA method, however can the same be done for indi?_**

Yes, indi can be set to 10 as well...

**_I also have some questions about the saltconcentration. In the settings the default is set to 0M, but in all/most of the examples it is set to 0.15M. Is there such a big differences between the two or in other words, why is the default not set to 0.15M?_**

typically, MD simulations are performed for systems with certain salt concentration. The 0.15M is completely arbitrary. The salt concentration should be adjusted according to what was used in the MD simulation.

**_And if I were to use the &alanine_sanning option with the cas_intdiel = 1 option, would this change a lot for my energy and decomposition results due to the assigned intdiel and indi values? Or is this a complete different calculation?_**

The decomposition values would change depending on the dielectric constant, same with the alanine scanning results. Now, the use of different dielectric constants depending on the amino acid mutated has been proven useful in the past (https://pubs.acs.org/doi/10.1021/acs.jcim.6b00734). I haven't seen something similar described for the decomposition values, although I would expect a  similar behavior based on the correlation between alanine scanning and decomposition values (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0137787#sec010)

**Comment by WoutVanEynde** [comment]
Okay, thank you for your answers. Just to make sure, for a system like PDB 1R4I (dimer with zinc fingers bound to DNA), parameters like this should be as representative as possible:

&general
  forcefields          = "leaprc.protein.ff19SB,leaprc.DNA.bsc1" (were used in md simulation)
  PBRadii              = 4 (mbondi3 is recommended for igb8)
&gb
  igb                  = 8 (DNA and protein)
  intdiel             = 10.0 (DNA in complex)
  saltcon            = 0.150 (salt concentration used in md simulation)
&pb
  ipb                  = 2						
  inp                  = 2
  indi                 = 10.0
  istrng              = 0.15 (salt concetration used in md simulation)
  radiopt            = 1
&alanine_scanning
  cas_intdiel=1
  
I only want to get the know the energy and its decomposition, no mutations needed. So I am not sure of the alanine scanning addition would change anything useful. 

Just one last question, is there anyway to calculate or give a rough estimation of how to get the dielectric constant of any complex, for example with a certain software or rule of thumb?
  
I am sorry for the questions, but I am just not that familiar with this field of study.
  
Warm regards and thanks in advance,
Wout Van Eynde

**Comment by marioernestovaldes** [comment]
Parameters look fine... Just remove the alanine scanning namelist fo you are not interested on that and add the &decomp namelist. Something like this:

```
&general
# (were used in md simulation)
forcefields = "leaprc.protein.ff19SB,leaprc.DNA.bsc1"
# (mbondi3 is recommended for igb8)
PBRadii = 4
/
&gb
# (DNA and protein)
igb = 8
# (DNA in complex)
intdiel = 10.0
# (salt concentration used in md simulation)
saltcon = 0.150
/
&pb
ipb = 2
inp = 2
indi = 10.0
# (salt concetration used in md simulation)
istrng = 0.15
radiopt = 1
/
&decomp
idecomp=2, dec_verbose=3,
print_res="within 4"
/
```

**_Just one last question, is there anyway to calculate or give a rough estimation of how to get the dielectric constant of any complex, for example with a certain software or rule of thumb?_**

We came up with a genreal strategy for this kind of question. Please, check:

[Manuscript_v5_JPC.pdf](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/12605489/Manuscript_v5_JPC.pdf)

https://www.researchgate.net/publication/367296926_Assessment_of_Different_Parameters_on_the_Accuracy_of_Computational_Alanine_Scanning_of_Protein-Protein_Complexes_with_the_Molecular_MechanicsGeneralized_Born_Surface_Area_Method

**Comment by WoutVanEynde** [comment]
Thank you for your quick answers and extra information, cannot thank you enough!
