### ISSUE TITLE
[Question]: using native AMBER files

### ISSUE THREAD

**Issue by camattelaer** [Valdes-Tresanco-MS/gmx_MMPBSA#446]
### My Question is...

Dear developer, I'm trying to use gmx_MMPBSA for analyzing MD simulations run by amber. If I'm looking through the files, e.g. parm_setup.py, my understanding is that GROMACS file are being transmuted into AMBER formats. Is this correct? Additionally, I've noticed the feature request for AMBER files types has already been closed on November 5, but I'm having trouble getting this to work. Is this only being released under v2 of gmx_MMPBSA? Is there a workaround currently, eg. AMBER -> GROMACS , so gmx_MMPBSA can then use the GROMACS files? Thank you in advance! Charles-Alexandre

**Comment by Valdes-Tresanco-MS** [comment]
Dear @camattelaer. Currently, native amber files are not supported. We are developing a new xBFreE suite to extend the gmx_MMPBSA's functionalities to other MD engines. We recently applied for funding since gmx_MMPBSA has no funding. I am the lead developer, and unfortunately, I had to move to another group and role because I have no funding. Right now, I have a lot of commitments that don't leave me time to work on it. We hope to have good news in March and to continue the development of gmx_MMPBSA and xBFreE. We are excited because we believe we have real possibilities but we must wait.

**Comment by camattelaer** [comment]
Oh that really is bad news. I really like the functionalities especially the interaction entropy and c2 entropy implementation. From my point of view, gmx_MMPBSA would be well on its way to become the succesor to the original MMPBSA.py! (Also qm_residues 'within' option is really nice!) I hope your funding comes through and wish yout the best of luck because gmx_MMPBSA is very promising and helpful imho!

I've just tried converting my amber files to gromacs using parmed and cpptraj and it seems to run fine. I'll continue to test to see if results are consistent. Before actually using for new analyses. :)

All the best! CA
