### ISSUE TITLE
[Question]: About the Force Fileds

### ISSUE THREAD

**Issue by allanlinzhang** [Valdes-Tresanco-MS/gmx_MMPBSA#471]
### My Question is...

When I run gmx_MMPBSA, I always get into the trouble that "ParameterError: Not all bond parameters found". From somewhere, it means wrong force field selection. So I want to know which force fields is supported in gmx_MMPBBSA?(My input is the protein-protein complex. I have tried AMBERGS force field, CHARMM27 all-atom force field, GROMOS96 43a1 force field and OPLS-AA/L)

**Comment by Valdes-Tresanco-MS** [comment]
gmx_MMPBSA support AMBER (any, for example, amber99SB, amber99SB-ILDN, amber14SB, and GAFF), CHARMM (27, 36), and OPLS (without gromos-like impropers since gmx_MMPBSA do no support these parameters). 
gmx_MMPBSA do not support any GROMOS force field since parmed does not support the topology conversion
