### ISSUE TITLE
[Question]: How to download gmx_MMPBSA_ana on Windows ?

### ISSUE THREAD

**Issue by allanlinzhang** [Valdes-Tresanco-MS/gmx_MMPBSA#473]
### My Question is...

I am astonished about the power of gmx_MMPBSA_ana. However, it doesn't work on my Linux , for the lack of graphical processing  interface. So I want to know how to download gmx_MMPBSA_ana on Windows.

**Comment by Valdes-Tresanco-MS** [comment]
Currently, gmx_MMPBSA is unavailable for Windows because it depends on gmx_MMPBSA core. Sorry about that.
We plan to separate gmx_MMPBSA_ana of gmx_MMPBSA core to make it independent of the OS and even implement it in web format. Unfortunately, we lack financial support, and the development team (including me, the main developer) has other jobs. So we lack time to develop new features; only answer questions, solve minimal bugs, and help our users.
We recently applied for funding and are hoping to win it now in April, because we have a lot of new features to implement.
