### ISSUE TITLE
suddenly stopped working

### ISSUE THREAD

**Issue by parazue** [Valdes-Tresanco-MS/gmx_MMPBSA#52]
ram@ram:~/Desktop/gmx_trial/output$ gmx_MMPBSA
Traceback (most recent call last):
  File "/home/ram/.local/bin/gmx_MMPBSA", line 7, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/ram/.local/lib/python2.7/site-packages/GMXMMPBSA/app.py", line 145
    sys.exit(app.exec())
                    ^
SyntaxError: invalid syntax

**Comment by Valdes-Tresanco-MS** [comment]
`gmx_MMPBSA` is not compatible with `Python2`. Please upgrade your python version

**Comment by parazue** [comment]
ram@ram:~$ gmx_MMPBSA
Traceback (most recent call last):
  File "/home/ram/.local/bin/gmx_MMPBSA", line 7, in <module>
    from GMXMMPBSA.app import gmxmmpbsa
  File "/home/ram/AmberTools21/amber20/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 131
    sys.exit(app.exec())
                    ^
SyntaxError: invalid syntax


Error in python 3.8

**Comment by Valdes-Tresanco-MS** [comment]
I need more context because I cannot reproduce the error. It seems that the `gmx_MMPBSA` executable is still configured with `Python2`. How did you install it? I would expect it to install in `/home/ram/AmberTools21/amber20/miniconda/lib/python3.8/site-packages/` instead of directly in amber's lib folder.

This error, is a problem of the python environment with which it is being executed, not of `gmx_MMPBSA` itself. Try to completely reinstall `gmx_MMPBSA` and see if the error is resolved. In extreme cases, a clean install should solve the problem. 
HTH!
Mario S
