### ISSUE TITLE
[Question]: a question. When do Decomposition analysis, selected some residues, but gmx_MMPBSA_ana do not show all of them.

### ISSUE THREAD

**Issue by guoshi22** [Valdes-Tresanco-MS/gmx_MMPBSA#545]
### My Question is...

When do Decomposition analysis, selected some residues, but gmx_MMPBSA_ana do not show all of them.

**Comment by guoshi22** [comment]
<img width="367" alt="图片1" src="https://github.com/user-attachments/assets/1a440514-bf35-43e3-8e17-941478c68bcf">
<img width="183" alt="图片2" src="https://github.com/user-attachments/assets/f8fde602-8047-4518-a9a5-49dff7715c9f">

**Comment by Valdes-Tresanco-MS** [comment]
Hi @guoshi22. This is because gmx_MMPBSA_ana defines a threshold for displaying any residue. This threshold was set to "alleviate" the overhead of the GUI by defining "all" residues without them contributing. You can change this setting in the initial dialog >> Decomposition Options (second panel) >> Per-residue threshold
