### ISSUE TITLE
[Question]: Impact of ionic strength in MMPBSA calculations

### ISSUE THREAD

**Issue by andrersalgueiro** [Valdes-Tresanco-MS/gmx_MMPBSA#547]
Hello,

I couldn´t understand the impact of the ionic strength in the ∆Gbind calculation for Poisson-Boltzmann. I performed replicates of the same protein:ligand complex and calculated the MMPBSA at both 0.150M and 0M, for each replicate. However, in one case I get lower energies in the presence of ionic strength, whereas in the other I get higher energies in the presence of the same ionic strength. 

Although the difference if not very large, it exists.

These are the obtained values:
Replicate 1: -28.48 kcal/mol (at 0.150M) and -28.55 kcal/mol (at 0M)
Replicate 2: -22.14 kcal/mol (at 0.150M) and -22.05 kcal/mol (at 0M)

Can anyone please help me understand this?

**Comment by Valdes-Tresanco-MS** [comment]
If you mean using the same MD and repeating the calculation several times, since this calculation is deterministic, you will get the same results (with variations in the order <1kcal) for the same MD using the same configuration. Some configurations can vary this, such as those that require energy minimization.
If by replicas you mean different MDs, that difference is due to the variation between one MD and another.
According to your information, the result for the calculation with ionic strength or not is expected. This is how it behaves for most systems.
To know how ionic strength is incorporated into the equation and its effect, you can consult chapters 4 and 6 of the Amber manual.
If there is a noticeable difference between one MD and another, then check what the structural variation is in both cases. This happens even at the level of the MD trajectory. Depending on the interval and the fraction you choose, you can get different energies. Then, you should justify why you chose that fraction and not another (for example, stable RMSD).

**Comment by andrersalgueiro** [comment]
Thank you so much for your quick response!

By replicates I mean different MDs of the same complex in the same conditions. So the only difference is the conformations that my protein and ligand adopt throughout the simulation time. For the MMPBSA, I used the entire trajectories of the respective replicates. 

I thought that the presence of ionic strength would always result in higher or lower energies for the same complex, rather than sometimes resulting in higher energies and sometimes in lower energies.

**Comment by JessicaRodrigues98** [comment]
Hello, I have a similar doubt. 

I performed my molecular dynamics simulations with the Amber99sb-ILDN force field, but with a neutral charge. When calculating the MMPBSA, I used an istrng=0.150 (because this is the value used in the lab). Could this affect my results? Could running the dynamics with a neutral concentration and then applying an ionic strength in the MMPBSA calculation change the outcome? When calculating without ionic strength for the same replica, the value also changed. I can’t understand how this parameter varies in the Poisson-Boltzmann equation. If an ionic strength of zero is expected to give a higher energy or not.

Thank you in advance!

**Comment by Valdes-Tresanco-MS** [comment]
> Thank you so much for your quick response!
> 
> By replicates I mean different MDs of the same complex in the same conditions. So the only difference is the conformations that my protein and ligand adopt throughout the simulation time. For the MMPBSA, I used the entire trajectories of the respective replicates.

Well, this is expected since the MD starts with different velocities. So, you can see structural variation when you make different replicates. If you are unhappy with the result, make several replicates and then calculate the average. This is a good approach.

> I thought that the presence of ionic strength would always result in higher or lower energies for the same complex, rather than sometimes resulting in higher energies and sometimes in lower energies.

The effect of the salt depends on the system's characteristics, like polarity and charge. It can increase or decrease the EEL, according to this property. So, the variation in the internal energy (TOTAL) will be given by the variation of EEL by the  electrostatic screening effects of the salt (by including the ionic strength/salt concentration in the calculation), usually small because VDWAALS tend to predominate

**Comment by Valdes-Tresanco-MS** [comment]
> Hello, I have a similar doubt.
> 
> I performed my molecular dynamics simulations with the Amber99sb-ILDN force field, but with a neutral charge. When calculating the MMPBSA, I used an istrng=0.150 (because this is the value used in the lab). Could this affect my results? 

Yes, but not as much as you might expect unless your system is highly charged, in which case you would have to take other considerations into account such as using non-linear PB if you want to include ionic strength. You can consult the amber manual as indicated above for more details. In most cases, it is irrelevant whether or not to include the term. Especially if the analysis is focused on comparing similar systems and not so much on reproducing absolute energy using lab conditions. For this, even the most robust and suitable alchemical methods have some problems.

> Could running the dynamics with a neutral concentration and then applying an ionic strength in the MMPBSA calculation change the outcome? When calculating without ionic strength for the same replica, the value also changed. I can’t understand how this parameter varies in the Poisson-Boltzmann equation. 

Yes. According to the results above, <0.1kcal is practically zero, so it does not represent a change that you should urgently consider. You can include it or not, I don't think that for this case any reviewer will focus on showing whether it has an effect or not. I don't think it affects your objective unless it is explicitly related to the term.

> If an ionic strength of zero is expected to give a higher energy or not.

The short answer depends. Whether it is greater or lesser depends on the characteristics of the system, as I mentioned in the comments above. Theoretically, ions have a screening effect, because they compete with water to establish interactions with polar residues. This is considered in the PB equation and has the dependencies that I mentioned before. Please consult the Amber manual for the respective equations and references.
