### ISSUE TITLE
getPDBfromTpr error

### ISSUE THREAD

**Issue by bhwl12** [Valdes-Tresanco-MS/gmx_MMPBSA#9]
The following error occurred: 
```
raise MMPBSA_Error('%s failed when querying %s' % (' '.join(trjconv), self.FILES.complex_tpr))
```
The command I used is following:
```
gmx_MMPBSA -O -i mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg 1 14 -ct md_0_10_noPBC.xtc -lm 6DO_bcc_gaff.mol2

```

The error in the make_top.log file is following:
```
Fatal error:
Index[76] 13524 is larger than the number of atoms in the
trajectory file (13523). There is a mismatch in the contents
of your -f, -s and/or -n files.
```
 Thanks!
[make_top.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/5699940/make_top.log)

**Comment by Valdes-Tresanco-MS** [comment]
Can you try another version of Gromacs?
Apparently this modified version of trjconv has problems in selecting the group in the index by name
The selected group is `GMXMMPBSA_REC_GMXMMPBSA_LIG` with index number [27], but the error is related to the index group [76]
```-------------------------------------------------- -----
Program: gmx trjconv, version 2020-MODIFIED
Source file: src / gromacs / tools / trjconv.cpp (line 920)

Fatal mistake:
Index [76] 13524 is larger than the number of atoms in the
trajectory file (13523). There is a mismatch in the contents
of your -f, -s and / or -n files.

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------- -----
Note that major changes are planned in future for trjconv, to improve usability and utility.
```

Did you try the tutorials? Did you get errors?

Make sure the tpr, the index and the dynamics are consistent. You can try to reproduce the error on your own by doing the following:
- create a group in the index that is protein + ligand
- generate a trajectory by selecting this group using the name instead of the group number in the index
- Save receptor, ligand and protein-ligand complex in pdb format from this trajectory

If you can reproduce the error, it would be a Gromacs bug.

**Comment by bhwl12** [comment]
Thanks for your reply! I found why the error occurred. I have two small molecules in the complex (GDP and 6DO).  The group number of 6DO (drug molecule) is larger than GDP (GDP group number: 13, 6DO group number: 14). 

best,
Yajun

**Comment by Valdes-Tresanco-MS** [comment]
Excellent...
Best wishes
